
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\andre\Desktop\faculdade\sistema de condominio\sistema_de_condominio_\interface\assets\frame6")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("950x680")
window.configure(bg = "#FFFFFF")
window.title("Sistema de Condomínio")

canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 680,
    width = 950,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    249.0,
    366.0,
    image=image_image_1
)

canvas.create_text(
    115.0,
    354.0,
    anchor="nw",
    text="horário",
    fill="#7C7C7C",
    font=("BeVietnamPro Medium", 10 * -1)
)

canvas.create_text(
    270.0,
    326.0,
    anchor="nw",
    text="09/05/2024",
    fill="#000000",
    font=("BeVietnamPro Medium", 14 * -1)
)

canvas.create_text(
    270.0,
    354.0,
    anchor="nw",
    text="Unidade Vinculada",
    fill="#7C7C7C",
    font=("BeVietnamPro Medium", 10 * -1)
)

canvas.create_text(
    115.0,
    322.0,
    anchor="nw",
    text="vinicius",
    fill="#000000",
    font=("BeVietnamPro MediumItalic", 14 * -1)
)

canvas.create_text(
    115.0,
    313.0,
    anchor="nw",
    text="nome",
    fill="#7C7C7C",
    font=("BeVietnamPro Medium", 10 * -1)
)

canvas.create_text(
    269.0,
    314.0,
    anchor="nw",
    text="data",
    fill="#7C7C7C",
    font=("BeVietnamPro Medium", 10 * -1)
)

canvas.create_text(
    270.0,
    366.0,
    anchor="nw",
    text="bloco ",
    fill="#000000",
    font=("BeVietnamPro Medium", 14 * -1)
)

canvas.create_text(
    360.0,
    366.0,
    anchor="nw",
    text="504",
    fill="#000000",
    font=("BeVietnamPro Medium", 14 * -1)
)

canvas.create_text(
    324.0,
    366.0,
    anchor="nw",
    text="apto",
    fill="#000000",
    font=("BeVietnamPro Medium", 14 * -1)
)

canvas.create_text(
    312.0,
    366.0,
    anchor="nw",
    text="3",
    fill="#000000",
    font=("BeVietnamPro Medium", 14 * -1)
)

canvas.create_text(
    115.0,
    366.0,
    anchor="nw",
    text="09h00 ",
    fill="#000000",
    font=("BeVietnamPro Medium", 14 * -1)
)

canvas.create_text(
    164.0,
    366.0,
    anchor="nw",
    text="ás",
    fill="#000000",
    font=("BeVietnamPro Medium", 14 * -1)
)

canvas.create_text(
    181.0,
    366.0,
    anchor="nw",
    text=" 21h30",
    fill="#000000",
    font=("BeVietnamPro Medium", 14 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=212.0,
    y=397.0,
    width=69.0,
    height=21.327281951904297
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    249.0,
    519.0,
    image=image_image_2
)

canvas.create_text(
    115.0,
    507.0,
    anchor="nw",
    text="horário",
    fill="#7C7C7C",
    font=("BeVietnamPro Medium", 10 * -1)
)

canvas.create_text(
    270.0,
    479.0,
    anchor="nw",
    text="09/05/2024",
    fill="#000000",
    font=("BeVietnamPro Medium", 14 * -1)
)

canvas.create_text(
    270.0,
    507.0,
    anchor="nw",
    text="Unidade Vinculada",
    fill="#7C7C7C",
    font=("BeVietnamPro Medium", 10 * -1)
)

canvas.create_text(
    115.0,
    475.0,
    anchor="nw",
    text="vinicius",
    fill="#000000",
    font=("BeVietnamPro MediumItalic", 14 * -1)
)

canvas.create_text(
    115.0,
    466.0,
    anchor="nw",
    text="nome",
    fill="#7C7C7C",
    font=("BeVietnamPro Medium", 10 * -1)
)

canvas.create_text(
    269.0,
    467.0,
    anchor="nw",
    text="data",
    fill="#7C7C7C",
    font=("BeVietnamPro Medium", 10 * -1)
)

canvas.create_text(
    270.0,
    519.0,
    anchor="nw",
    text="bloco ",
    fill="#000000",
    font=("BeVietnamPro Medium", 14 * -1)
)

canvas.create_text(
    360.0,
    519.0,
    anchor="nw",
    text="504",
    fill="#000000",
    font=("BeVietnamPro Medium", 14 * -1)
)

canvas.create_text(
    324.0,
    519.0,
    anchor="nw",
    text="apto",
    fill="#000000",
    font=("BeVietnamPro Medium", 14 * -1)
)

canvas.create_text(
    312.0,
    519.0,
    anchor="nw",
    text="3",
    fill="#000000",
    font=("BeVietnamPro Medium", 14 * -1)
)

canvas.create_text(
    115.0,
    519.0,
    anchor="nw",
    text="09h00 ",
    fill="#000000",
    font=("BeVietnamPro Medium", 14 * -1)
)

canvas.create_text(
    164.0,
    519.0,
    anchor="nw",
    text="ás",
    fill="#000000",
    font=("BeVietnamPro Medium", 14 * -1)
)

canvas.create_text(
    181.0,
    519.0,
    anchor="nw",
    text=" 21h30",
    fill="#000000",
    font=("BeVietnamPro Medium", 14 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=212.0,
    y=550.0,
    width=69.0,
    height=21.327281951904297
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    249.0,
    213.0,
    image=image_image_3
)

canvas.create_text(
    115.0,
    201.0,
    anchor="nw",
    text="horário",
    fill="#7C7C7C",
    font=("BeVietnamPro Medium", 10 * -1)
)

canvas.create_text(
    270.0,
    173.0,
    anchor="nw",
    text="09/05/2024",
    fill="#000000",
    font=("BeVietnamPro Medium", 14 * -1)
)

canvas.create_text(
    270.0,
    201.0,
    anchor="nw",
    text="Unidade Vinculada",
    fill="#7C7C7C",
    font=("BeVietnamPro Medium", 10 * -1)
)

canvas.create_text(
    115.0,
    169.0,
    anchor="nw",
    text="vinicius",
    fill="#000000",
    font=("BeVietnamPro MediumItalic", 14 * -1)
)

canvas.create_text(
    115.0,
    160.0,
    anchor="nw",
    text="nome",
    fill="#7C7C7C",
    font=("BeVietnamPro Medium", 10 * -1)
)

canvas.create_text(
    269.0,
    161.0,
    anchor="nw",
    text="data",
    fill="#7C7C7C",
    font=("BeVietnamPro Medium", 10 * -1)
)

canvas.create_text(
    270.0,
    213.0,
    anchor="nw",
    text="bloco ",
    fill="#000000",
    font=("BeVietnamPro Medium", 14 * -1)
)

canvas.create_text(
    360.0,
    213.0,
    anchor="nw",
    text="504",
    fill="#000000",
    font=("BeVietnamPro Medium", 14 * -1)
)

canvas.create_text(
    324.0,
    213.0,
    anchor="nw",
    text="apto",
    fill="#000000",
    font=("BeVietnamPro Medium", 14 * -1)
)

canvas.create_text(
    312.0,
    213.0,
    anchor="nw",
    text="3",
    fill="#000000",
    font=("BeVietnamPro Medium", 14 * -1)
)

canvas.create_text(
    115.0,
    213.0,
    anchor="nw",
    text="09h00 ",
    fill="#000000",
    font=("BeVietnamPro Medium", 14 * -1)
)

canvas.create_text(
    164.0,
    213.0,
    anchor="nw",
    text="ás",
    fill="#000000",
    font=("BeVietnamPro Medium", 14 * -1)
)

canvas.create_text(
    181.0,
    213.0,
    anchor="nw",
    text=" 21h30",
    fill="#000000",
    font=("BeVietnamPro Medium", 14 * -1)
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=212.0,
    y=244.0,
    width=69.0,
    height=21.327281951904297
)

canvas.create_text(
    45.0,
    66.0,
    anchor="nw",
    text="hoje",
    fill="#8EBC4F",
    font=("BeVietnamPro SemiBold", 45 * -1)
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=639.0,
    y=279.0,
    width=115.0,
    height=40.78125
)

canvas.create_text(
    539.0,
    66.0,
    anchor="nw",
    text="Pesquisa",
    fill="#8EBC4F",
    font=("BeVietnamPro Bold", 45 * -1)
)

canvas.create_text(
    539.0,
    144.0,
    anchor="nw",
    text="nome:",
    fill="#000000",
    font=("BeVietnamPro SemiBold", 17 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    695.0,
    181.66262912750244,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=548.0,
    y=166.0,
    width=294.0,
    height=29.325258255004883
)

canvas.create_text(
    539.0,
    203.0,
    anchor="nw",
    text="bloco:",
    fill="#000000",
    font=("BeVietnamPro SemiBold", 17 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    609.0,
    240.66262912750244,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=548.0,
    y=225.0,
    width=122.0,
    height=29.325258255004883
)

canvas.create_text(
    711.0,
    203.0,
    anchor="nw",
    text="apartamento:",
    fill="#000000",
    font=("BeVietnamPro SemiBold", 17 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    781.0,
    240.66262912750244,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=720.0,
    y=225.0,
    width=122.0,
    height=29.325258255004883
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=69.0,
    y=34.0,
    width=30.0,
    height=15.0
)

canvas.create_text(
    724.0,
    25.0,
    anchor="nw",
    text="Liberar visitantes",
    fill="#B9B9B9",
    font=("BeVietnamPro Light", 19 * -1)
)

canvas.create_rectangle(
    474.0,
    90.0,
    476.0,
    590.0,
    fill="#FFFFFF",
    outline="")
window.resizable(False, False)
window.mainloop()
